### ISSUE TITLE
The notion page is not public now....

### ISSUE THREAD

**Issue by Yolandasu1990** [WeTransfer/product-engineering-career-framework#2] opened 2022-07-27 05:10 UTC
Hi Bastiaan, good day to you! I have been read the career framework of WeTransfer last week, and it is so inspiring! When I would like to dig it more, seems the notion page is not public now....I feel super frustrated. I'm not a tech person, but a HR wants to create a framework for our tech team. I really really hope I can read it again... SOS. T-T @bastiaanterhorst 

https://www.notion.so/888bd307af1e4c5a9b6a947191e6a898?v=adb383817e304714a042eabc3366c79d
https://www.notion.so/0e6e6b3b6c32407cb6b964ea5a429f75?v=435c054d18b94a7f95fb90f9400f2111

**Comment by jwolski2** [comment] 2022-08-02 08:25
Hey Yolanda 👋🏾 . Thanks for filing the issue. I can get this sorted out for you!

**Comment by jwolski2** [comment] 2022-08-02 09:43
Hi again. It looks like your issue is a duplicate of https://github.com/WeTransfer/product-engineering-career-framework/issues/1. I'm going to close out your issue. For any updates, you can follow along there.

**Closed by jwolski2** 2022-08-02 09:43 UTC
